### ISSUE TITLE
Modernizing The Repo

### ISSUE THREAD

**Issue by vramana** [karthikmy9/BullsEye#1]
Todos

- [x] Linting (eslint recommended)
- [ ] Linting Advanced (eslint airbnb)
- [ ] Callbacks to Promises
- [ ] Use ES6 features
- [ ] Jest
- [ ] Flow

**Comment by vramana** [comment]
Hey, Any updates?

**Comment by karthikmy9** [comment]
Hi ramana, yea working presently to change code to es6.
